version: "2"
services:
  jenkins:
    container_name: jenkins
    image: jenkinsci/blueocean
    environment:
      - DOCKER_HOST=tcp://172.21.35.113:2375
      - K8S_HOST=tcp://192.168.65.3:6443
    user: root
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:8443:8443"
      - "0.0.0.0:50000:50000"
    volumes:
      - /var/jenkins_home
  mysql:
    container_name: mysql
    image: mysql:5.7.31
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "0.0.0.0:3306:3306"
  gogs-data:
    container_name: gogs-data
    image: gogs/gogs
    entrypoint:
      - /bin/true
  gogs:
    container_name: gogs
    image: gogs/gogs
    volumes:
        from:
            - gogs-data
  docker-remote-api:
    container_name: docker-remote-api
    image: jarkt/docker-remote-api
    ports:
      - "0.0.0.0:2375:2375"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock