version: "2"
services:
  jenkins:
    container_name: jenkins
    image: jenkinsci/blueocean
    environment:
      - DOCKER_HOST=tcp://172.21.35.113:2375
      - K8S_HOST=tcp://192.168.65.3:6443
    user: root
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:8443:8443"
      - "0.0.0.0:50000:50000"
    volumes:
      - /var/jenkins_home
  mysql:
    container_name: mysql
    image: mysql:5.7.31
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    ports:
      - "0.0.0.0:3306:3306"
  s3-ninja:
    container_name: s3-ninja
    image: scireum/s3-ninja:6.5.1
    ports:
      - "0.0.0.0:9444:9000"
  gogs:
    container_name: gogs
    image: gogs/gogs:0.12
    ports:
      - "0.0.0.0:22:22"
      - "0.0.0.0:3000:3000"
    volumes:
      - gogs-data:/data
  docker-remote-api:
    container_name: docker-remote-api
    image: jarkt/docker-remote-api
    ports:
        - "0.0.0.0:2375:2375"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
volumes:
    gogs-data:
        name: gogs-data
